---
- name: Add required dependencies.
  ansible.builtin.package:
    name:
      - apt-transport-https
      - python3-elasticsearch
      - gpg
    state: present

- name: Add fluent-bit repo
  block:
    - name: Somerepo |no apt key
      ansible.builtin.apt_key:
        url: https://packages.fluentbit.io/fluentbit.key
        keyring: /usr/share/keyrings/fluentbit-keyring.gpg

    - name: Somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
        state: present
