---
- name: Restart node_exporter
  listen: "restart node_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode

- name: Reload Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded
  delegate_to: "{{ item }}"
  with_inventory_hostnames:
    - all:prometheus_servers
